{% set name = "dbt-core" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_core-{{ version }}.tar.gz
  sha256: 38c931dd5206fdb11a9db1decf1075ce891ad9f4692bd00a9ba760a6cfe4358d

build:
  entry_points:
    - dbt = dbt.cli.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - agate
    - jinja2
    - mashumaro
    - click 
    - networkx
    - protobuf
    - requests
    - snowplow-tracker
    - pathspec 
    - sqlparse
    - dbt-extractor
    - dbt-semantic-interfaces
    - dbt-common
    - dbt-adapters
    - packaging
    - pytz
    - pyyaml
    - daff
    - typing-extensions

test:
  imports:
    - dbt
  commands:
    - pip check
    - dbt --help
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-core
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  #license_file: License.md
  dev_url: https://github.com/dbt-labs/dbt-core
  doc_url: https://github.com/dbt-labs/dbt-core/tree/main/docs
extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/63495
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
